version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a"
    - "< 9"
